import fs from "node:fs";
// Always use the latest available version of Unicode!
// https://tc39.github.io/ecma262/#sec-conformance
import packageJson from "../package.json" with { type: "json" };

const unicodePackageNamePrefix = "@unicode/unicode-";
const unicodePackageName = Object.keys(packageJson.devDependencies).find(name =>
  name.startsWith(unicodePackageNamePrefix)
);

const start = (
  await import(`${unicodePackageName}/Binary_Property/ID_Start/code-points.js`)
).default.filter(function (ch: number) {
  return ch > 0x7f;
});
let last = -1;
const cont = (
  await import(
    `${unicodePackageName}/Binary_Property/ID_Continue/code-points.js`
  )
).default.filter(function (ch: number) {
  return ch > 0x7f && search(start, ch, last + 1) === -1;
});

function search(arr: number[], ch: number, starting: number) {
  for (let i = starting; arr[i] <= ch && i < arr.length; last = i++) {
    if (arr[i] === ch) return i;
  }
  return -1;
}

function esc(code: number) {
  const hex = code.toString(16);
  if (hex.length <= 2) return "\\x" + hex.padStart(2, "0");
  else return "\\u" + hex.padStart(4, "0");
}

function generate(chars: number[]) {
  const supplementary = [];
  let re = "";
  for (let i = 0, at = 0x10000; i < chars.length; i++) {
    const from = chars[i];
    let to = from;
    while (i < chars.length - 1 && chars[i + 1] === to + 1) {
      i++;
      to++;
    }
    if (to <= 0xffff) {
      if (from === to) re += esc(from);
      else if (from + 1 === to) re += esc(from) + esc(to);
      else re += esc(from) + "-" + esc(to);
    } else {
      supplementary.push(from - at, to - from);
      at = to;
    }
  }
  return { bmp: re, supplementary };
}

const startData = generate(start);
const contData = generate(cont);

fs.writeFileSync(
  new URL("../data/index.ts", import.meta.url),
  `
// ## Character categories

// Big ugly regular expressions that match characters in the
// whitespace, identifier, and identifier-start categories. These
// are only applied when a character is found to actually have a
// code point between 0x80 and 0xffff.
// Generated by \`scripts/generate-identifier-regex.ts\`.
export const bmpIdentifierStartChars = "${startData.bmp}";
export const bmpIdentifierChars = "${contData.bmp}";

// These are a run-length and offset-encoded representation of the
// >0xffff code points that are a valid part of identifiers. The
// offset starts at 0x10000, and each pair of numbers represents an
// offset to the next range, and then a size of the range. They were
// generated by \`scripts/generate-identifier-regex.ts\`.
export const supplementaryIdentifierStartCodes = ${JSON.stringify(startData.supplementary)};
export const supplementaryIdentifierCodes = ${JSON.stringify(contData.supplementary)};
`.trimStart()
);
